// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecomendationsAPI.Data;

#nullable disable

namespace RecomendationsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RecomendationsAPI.Models.Comment", b =>
                {
                    b.Property<int>("id_comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("id_client")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("id_dev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_ranking")
                        .HasColumnType("int");

                    b.Property<short>("rate")
                        .HasColumnType("smallint");

                    b.HasKey("id_comment");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RecomendationsAPI.Models.Ranking", b =>
                {
                    b.Property<int>("id_ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("count_done")
                        .HasColumnType("smallint");

                    b.Property<string>("id_dev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_ranking");

                    b.ToTable("Rankings");
                });
#pragma warning restore 612, 618
        }
    }
}
